version: '2'
services:
    sanka2-app:
        image: sanka2
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://sanka2-mysql:3306/sanka2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=sanka2-elasticsearch:9300
        ports:
            - 8080:8080
    sanka2-mysql:
        extends:
            file: mysql.yml
            service: sanka2-mysql
    sanka2-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: sanka2-elasticsearch
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
